### ISSUE TITLE
Cart temp controller

### ISSUE THREAD

**Issue by GuroKung** [SixthFloor/FECS-Web#43]
provide controller for the cart to with the cart page

**Comment by GuroKung** [comment]
now it's for temporary use waiting for API, if you refresh the page the data will gone

user can add/remove product from cart and see the information and total price
on the cart page

**Comment by vincentvictor** [comment]
Is it still temporary data?  When we add the same  furniture to cart with quantity 1. For example, I repeat adding a bed quantity 1 for 5 times. In cart page, it shows 5 line item and it does not make sense because it provides column quantity. It should be only 1 line item (same bed) and quantity of 5.
